// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeCube.Models;

public partial class PreferedIngredient
{
    public int PreferIngredientId { get; set; }

    public string UserId { get; set; }

    public int? IngredientId { get; set; }
}