// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeCubeWebService.Models;

public partial class RecipeIngredient
{
    public int RecipeIngredientId { get; set; }

    public int? RecipeId { get; set; }

    public int? IngredientId { get; set; }

    public decimal? Quantity { get; set; }
}